CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(64) NOT NULL,
    user_name  VARCHAR(32) NOT NULL,
    UNIQUE (user_email, user_name)
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    event_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_annotation         VARCHAR(2000)               NOT NULL,
    event_description        VARCHAR(7000)               NOT NULL,
    event_paid               BOOLEAN     DEFAULT FALSE,
    event_state              VARCHAR(32) DEFAULT 'PENDING',
    event_title              VARCHAR(120)                NOT NULL,
    event_location_lat       FLOAT                       NOT NULL,
    event_location_lon       FLOAT                       NOT NULL,
    event_initiator_id       BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    event_category_id        BIGINT                      REFERENCES categories (category_id) ON DELETE SET NULL,
    event_participant_limit  INTEGER     DEFAULT 0,
    event_request_moderation BOOLEAN     DEFAULT TRUE,
    event_date               TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_created_on         TIMESTAMP WITHOUT TIME ZONE,
    event_published_on       TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS compilation
(
    compilation_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_pinned BOOLEAN DEFAULT FALSE,
    compilation_title  VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id       BIGINT REFERENCES compilation (compilation_id),
    compilation_event_id BIGINT REFERENCES events (event_id),
    PRIMARY KEY (compilation_id, compilation_event_id)
);

CREATE TABLE IF NOT EXISTS participation
(
    participation_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participation_requester_id BIGINT REFERENCES users (user_id),
    participation_event_id     BIGINT REFERENCES events (event_id),
    participation_created_on   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    participation_status       VARCHAR(120)                NOT NULL,
    UNIQUE (participation_requester_id, participation_event_id)
)

