CREATE TABLE IF NOT EXISTS hits
(
    hit_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(50)                 NOT NULL,
    ip        VARCHAR(16)                 NOT NULL,
    uri       VARCHAR(255)                NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);